"""add deployment modality

Revision ID: 0445e221cef9
Revises: e0c70aacf57d
Create Date: 2026-06-28 23:55:38.931346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0445e221cef9'
down_revision: Union[str, Sequence[str], None] = 'e0c70aacf57d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployments', sa.Column('modality', sa.String(), server_default='tabular', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deployments', 'modality')
    # ### end Alembic commands ###
