"""add hyperparameters and scale_features to jobs

Revision ID: 09d13aff90d1
Revises: 81fe91fe4402
Create Date: 2026-06-27 23:41:44.755845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09d13aff90d1'
down_revision: Union[str, Sequence[str], None] = '81fe91fe4402'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('hyperparameters', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'hyperparameters')
    # ### end Alembic commands ###
