"""make job target_column nullable

Revision ID: 3c19c4542112
Revises: 96c0b33f4145
Create Date: 2026-06-28 22:37:54.603223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c19c4542112'
down_revision: Union[str, Sequence[str], None] = '96c0b33f4145'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'target_column',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'target_column',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
