"""add scale_features to jobs

Revision ID: 81fe91fe4402
Revises: e713e680af62
Create Date: 2026-06-27 23:23:06.742326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81fe91fe4402'
down_revision: Union[str, Sequence[str], None] = 'e713e680af62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('scale_features', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'scale_features')
    # ### end Alembic commands ###
